apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-web
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - rbac.yaml
  - configmap-catalog.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - networkpolicy.yaml
