apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-web-manager
  namespace: app-web
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-web-manager
  namespace: app-web
subjects:
  - kind: ServiceAccount
    name: app-web-manager
    namespace: app-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-web-manager
