apiVersion: v1
kind: Service
metadata:
  name: app-web-manager
  namespace: app-web
spec:
  selector:
    app.kubernetes.io/name: app-web-manager
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
