apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-web-manager
  namespace: app-web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-web-session
  namespace: app-web
automountServiceAccountToken: false
